### PR TITLE
Update experimental.py

### PR DESCRIPTION
**Pull request by jrtwolski**
Blocking bug - one line change.

### CODE REVIEW

**Comment by jrtwolski** [comment]
Blocking bug

**Comment by kadirnar** [comment]
Thanks for your contribution! We'll check and verify the code asap.

**Comment by jrtwolski** [comment]
Hello! Could you commit the fix?

**Comment by kadirnar** [comment]
> Hello! Could you commit the fix?

It was a very busy week. Sorry for replying late. There is a problem with downloading the model. Your suggestion doesn't solve this.

```
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

**Comment by jrtwolski** [comment]
I am sure that the fix works - we have been using in for three weeks now.

**Comment by kadirnar** [comment]
> I am sure that the fix works - we have been using in for three weeks now.

I will also add command-line support this week. Thank you for choosing the pip version.

**Pull request closed without merging**
